### ISSUE TITLE
Multiple Tenants/Orgs Fails to Upload Data to InfluxDB2

### ISSUE THREAD

**Issue by MarvinPU36** [jorgedlcruz/veeam-backup-for-office365-grafana#13]
Doesn't pull data when there are multiple organizations (tenants) within Veeam M365 on Veeam M365 v7
`Error: failed to write data: 400 Bad Request: unable to parse 'veeam_office365_jobs,veeamjobname=SharePoint,\ OneDrive,\ and\ Teams,bottleneck=Source totalDuration=2324,status=1,processingRate=2770350,readRate=2446599,writeRate=3329979,transferredData=6432304892,processedObjects=393 1689665924': missing tag value`

**Comment by MarvinPU36** [comment]
The issue is resolved.  The Job named can NOT have ","   Removed the comma and the script works.

**Comment by mcbrineellis** [comment]
I think the issue here is that the spaces are being escaped properly but commas are not.

```
nameJob=$(echo "$veeamJobsUrl" | jq --raw-output ".[$arrayJobs].name" | awk '{gsub(/ /,"\\ ");print}')
```
Adjusting the script so awk will escape commas seems to do the trick:
```
nameJob=$(echo "$veeamJobsUrl" | jq --raw-output ".[$arrayJobs].name" | awk '{gsub(/ /,"\\ "); gsub(/,/, "\\,"); print}')
```
