### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by axeteg** [jorgedlcruz/veeam-backup-for-office365-grafana#3]
Hi

When trying to run the veeam_office365.sh I recieve

./veeam_office365.sh: line 35: jq: command not found
(23) Failed writing body
./veeam_office365.sh: line 44: jq: command not found
./veeam_office365.sh: line 66: jq: command not found
./veeam_office365.sh: line 82: jq: command not found
./veeam_office365.sh: line 98: jq: command not found
./veeam_office365.sh: line 181: jq: command not found

Cant really find out what im missing

**Comment by jorgedlcruz** [comment]
Hello,
Which OS are you using? If Debian/Ubuntu try apt-get install jq, if RHEL/CentOS yum install jq

Best regards

**Comment by axeteg** [comment]
Well, that was easy, but I then ran into the next problem


{"error":"unable to parse 'veeam_office365_jobs,veeamjobname="Company Name" Full Sharepoint,bottleneck=Target totalDuration=153,status=2,processingRate=0.0,readRate=,writeRate=0.,transferredData=0.,processedObjects=37 1543718071': invalid field format"}
(standard_in) 1: syntax error
HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 2b9881a6-4a1d-11e9-9059-005056aff49d
X-Influxdb-Build: OSS
X-Influxdb-Error: unable to parse 'veeam_office365_jobs,veeamjobname="Company Name" Full Sharepoint,bottleneck=Target totalDuration=158,status=2,processingRate=0.0,readRate=,writeRate=0.,transferredData=0.,processedObjects=37 1543717318': invalid field format
X-Influxdb-Version: 1.7.4
X-Request-Id: 2b9881a6-4a1d-11e9-9059-005056aff49d
Date: Tue, 19 Mar 2019 08:01:15 GMT
Content-Length: 247

Seems like I get the same error for every field

**Comment by jorgedlcruz** [comment]
Please send me the full errors, without Company Name or anything to veeam@jorgedelacruz.es Thank you

**Comment by jorgedlcruz** [comment]
Hello,
If you have upgraded to VBO 3.0, please download the new script for 3.0, and the Dashboard and let me know.

**Comment by jorgedlcruz** [comment]
Closing it, for now, let me know if you still have the issue on another ticket :)
